version: "2"
volumes:
  pgdata:
  cache:
services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - postgres_conn
    ports:
      - "5434:5432"
    env_file: .env
  import-osm:
    image: "openmaptiles/import-osm:0.5"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
    - postgres_conn
    volumes:
     - ./data:/import
     - ./build:/mapping
     - cache:/cache
  import-sql:
    image: "openmaptiles/import-sql:0.8"
    env_file: .env
    networks:
    - postgres_conn
    volumes:
     - ./build:/sql
  import-wikidata:
    image: "openmaptiles/import-wikidata:0.1"
    env_file: .env
    command: import-wikidata
    networks:
    - postgres_conn
    volumes:
     - ./wikidata:/import
  openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:0.9.2"
    env_file: .env
    networks:
    - postgres_conn
    volumes:
     - .:/tileset
     - ./build:/sql
  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:0.1.1"
    volumes:
    - ./data:/export
    - ./build/openmaptiles.tm2source:/tm2source
    networks:
    - postgres_conn
    env_file: .env
    environment:
      BBOX: ${BBOX}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
  postserve:
    image: "openmaptiles/postserve:0.2"
    env_file: .env
    networks:
     - postgres_conn
    ports:
    - "8090:8080"
    volumes:
     - ./build/openmaptiles.tm2source:/mapping

networks:
  postgres_conn:
    driver: bridge
